export EDITOR=nvim
export DOCKER_HOST="unix:///run/user/$UID/podman/podman.sock"
export TESTCONTAINERS_RYUK_DISABLED="true"
export BROWSER=none
export MANPAGER='nvim +Man!'
export KUBECONFIG="/home/stcarolas/.config/k3s.yaml"
export TERM=xterm
export _JAVA_AWT_WM_NONREPARENTING=1
export KIND_EXPERIMENTAL_PROVIDER=podman
